// Generated by CoffeeScript 1.4.0
(function() {

  jstd.for_each = function(first, last, f) {
    while (first.neq(last)) {
      f(first.get());
      first.next();
    }
    return f;
  };

  jstd.min = function(obj1, obj2) {
    if (typeof obj1 === "number" || typeof obj1 === "bool" || typeof obj1 === "string" || obj1 instanceof Array) {
      if (!(obj2 < obj1)) {
        return obj1;
      } else {
        return obj2;
      }
    }
    if (!(obj2.lt(obj1))) {
      return obj1;
    } else {
      return obj2;
    }
  };

  jstd.max = function(obj1, obj2) {
    if (typeof obj1 === "number" || typeof obj1 === "bool" || typeof obj1 === "string" || obj1 instanceof Array) {
      if (obj1 < obj2) {
        return obj2;
      } else {
        return obj1;
      }
    }
    if (obj1.lt(obj2)) {
      return obj2;
    } else {
      return obj1;
    }
  };

  jstd.copy = function(first, last, it) {
    first = first.clone();
    it = it.clone();
    while (first.neq(last)) {
      it.set(first.get());
      first.next();
      it.next();
    }
    return it;
  };

  jstd.fill_n = function(first, n, v) {
    var i, _results;
    first = first.clone();
    i = 0;
    _results = [];
    while (i < n) {
      first.set(v);
      first.next();
      _results.push(i++);
    }
    return _results;
  };

}).call(this);
