// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jstd.exception = (function() {

    function exception() {
      this.message = this.what();
    }

    exception.prototype.what = function() {
      return "exception";
    };

    return exception;

  })();

  jstd.logic_error = (function(_super) {

    __extends(logic_error, _super);

    function logic_error() {
      return logic_error.__super__.constructor.apply(this, arguments);
    }

    logic_error.prototype.what = function() {
      return "logic_error";
    };

    return logic_error;

  })(jstd.exception);

  jstd.out_of_range = (function(_super) {

    __extends(out_of_range, _super);

    function out_of_range() {
      return out_of_range.__super__.constructor.apply(this, arguments);
    }

    out_of_range.prototype.what = function() {
      return "out_of_range";
    };

    return out_of_range;

  })(jstd.logic_error);

}).call(this);
