// Generated by CoffeeScript 1.4.0
(function() {

  jstd.accumulate = function(first, last, init) {
    if (init == null) {
      init = 0;
    }
    first = first.clone();
    while (first.neq(last)) {
      init = init + first.get();
      first.next();
    }
    return init;
  };

}).call(this);
